---
- name: "Initial Configuration Push"
  hosts: "ptxrouters"
  gather_facts: False
  vars_files:
    - "lab_vars_cleanup.yml"
  roles:
    - role: "network_interface_configuration"
      tags: "interfaces"
    - role: "junos_isis_config"
      tags: "isis"
    - role: "junos_macsec_config"
      tags: "macsec"
  post_tasks:
    - name: "Remove {{ macsec_interface }} configuration"
      junos_config:
        lines:
          - "delete interfaces {{ macsec_interface }} unit 0"
          - "delete interfaces et-0/0/0 disable"
