---
- name: "Initial Configuration Push"
  hosts: "ptxrouters"
  gather_facts: False
  vars_files:
    - "lab_vars.yml"
  roles:
    - role: "network_interface_configuration"
      tags: "interfaces"
    - role: "junos_isis_config"
      tags: "isis"
