---
- name: "Initial Configuration Push"
  hosts: "ptxrouters"
  gather_facts: False
  vars_files:
    - "lab_vars.yml"
  roles:
    - role: "network_interface_configuration"
      tags: "interfaces"
    - role: "junos_isis_config"
      tags: "isis"
    - role: "junos_static_routes"
      tags: "static"
    - role: "junos_macsec_config"
      tags: "macsec"
  post_tasks:
    - name: "Shutdown ZR link"
      junos_config:
        lines:
          - "set interfaces et-0/0/0 disable"
