---
interfaces:
  - name: "et-0/0/0"
    description: "toPTX2et0_0_0"
    unit: "0"
    ipv4:
      - address: "10.12.0.0/31"
    type: "p2p"
  - name: "et-0/0/2"
    description: "toTestSet"
    unit: "0"
    ipv4:
      - address: "10.10.2.1/24"
    type: "p2p"
  - name: "lo0"
    description: "loopback"
    unit: "0"
    ipv4:
      - address: "1.1.1.1/32"
    type: "loop"
  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "1"
    ipv4:
      - address: "10.120.1.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "2"
    ipv4:
      - address: "10.120.2.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "3"
    ipv4:
      - address: "10.120.3.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "4"
    ipv4:
      - address: "10.120.4.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "5"
    ipv4:
      - address: "10.120.5.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "6"
    ipv4:
      - address: "10.120.6.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "7"
    ipv4:
      - address: "10.120.7.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "8"
    ipv4:
      - address: "10.120.8.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "9"
    ipv4:
      - address: "10.120.9.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "10"
    ipv4:
      - address: "10.120.10.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "11"
    ipv4:
      - address: "10.120.11.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "12"
    ipv4:
      - address: "10.120.12.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "13"
    ipv4:
      - address: "10.120.13.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "14"
    ipv4:
      - address: "10.120.14.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "15"
    ipv4:
      - address: "10.120.15.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "16"
    ipv4:
      - address: "10.120.16.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "17"
    ipv4:
      - address: "10.120.17.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "18"
    ipv4:
      - address: "10.120.18.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "19"
    ipv4:
      - address: "10.120.19.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "20"
    ipv4:
      - address: "10.120.20.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "21"
    ipv4:
      - address: "10.120.21.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "22"
    ipv4:
      - address: "10.120.22.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "23"
    ipv4:
      - address: "10.120.23.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "24"
    ipv4:
      - address: "10.120.24.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "25"
    ipv4:
      - address: "10.120.25.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "26"
    ipv4:
      - address: "10.120.26.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "27"
    ipv4:
      - address: "10.120.27.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "28"
    ipv4:
      - address: "10.120.28.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "29"
    ipv4:
      - address: "10.120.29.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "30"
    ipv4:
      - address: "10.120.30.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "31"
    ipv4:
      - address: "10.120.31.0/31"
    type: "p2p"

  - name: "et-0/0/1"
    description: "toPTX2et_0_0_1"
    unit: "32"
    ipv4:
      - address: "10.120.32.0/31"
    type: "p2p"


physical_interfaces: "{{ interfaces }}"
logical_interfaces: "{{ interfaces }}"
isis_interfaces: "{{ interfaces }}"
isis_settings:
  loopback_unit: "0"
  loopback_clns_address: "49.0001.0001.0001.0001.0001.00"
  level1_disable: True
isis_wide_metrics: True

static_routes:
  - route: "10.20.2.1/32"
    next_hop: "10.120.1.1"

  - route: "10.20.2.2/32"
    next_hop: "10.120.2.1"

  - route: "10.20.2.3/32"
    next_hop: "10.120.3.1"

  - route: "10.20.2.4/32"
    next_hop: "10.120.4.1"

  - route: "10.20.2.5/32"
    next_hop: "10.120.5.1"

  - route: "10.20.2.6/32"
    next_hop: "10.120.6.1"

  - route: "10.20.2.7/32"
    next_hop: "10.120.7.1"

  - route: "10.20.2.8/32"
    next_hop: "10.120.8.1"

  - route: "10.20.2.9/32"
    next_hop: "10.120.9.1"

  - route: "10.20.2.10/32"
    next_hop: "10.120.10.1"

  - route: "10.20.2.11/32"
    next_hop: "10.120.11.1"

  - route: "10.20.2.12/32"
    next_hop: "10.120.12.1"

  - route: "10.20.2.13/32"
    next_hop: "10.120.13.1"

  - route: "10.20.2.14/32"
    next_hop: "10.120.14.1"

  - route: "10.20.2.15/32"
    next_hop: "10.120.15.1"

  - route: "10.20.2.16/32"
    next_hop: "10.120.16.1"

  - route: "10.20.2.17/32"
    next_hop: "10.120.17.1"

  - route: "10.20.2.18/32"
    next_hop: "10.120.18.1"

  - route: "10.20.2.19/32"
    next_hop: "10.120.19.1"

  - route: "10.20.2.20/32"
    next_hop: "10.120.20.1"

  - route: "10.20.2.21/32"
    next_hop: "10.120.21.1"

  - route: "10.20.2.22/32"
    next_hop: "10.120.22.1"

  - route: "10.20.2.23/32"
    next_hop: "10.120.23.1"

  - route: "10.20.2.24/32"
    next_hop: "10.120.24.1"

  - route: "10.20.2.25/32"
    next_hop: "10.120.25.1"

  - route: "10.20.2.26/32"
    next_hop: "10.120.26.1"

  - route: "10.20.2.27/32"
    next_hop: "10.120.27.1"

  - route: "10.20.2.28/32"
    next_hop: "10.120.28.1"

  - route: "10.20.2.29/32"
    next_hop: "10.120.29.1"

  - route: "10.20.2.30/32"
    next_hop: "10.120.30.1"

  - route: "10.20.2.31/32"
    next_hop: "10.120.31.1"

  - route: "10.20.2.32/32"
    next_hop: "10.120.32.1"

macsec_cas:
  - name: "CA1"
    security_mode: "static-cak"
    cipher: "gcm-aes-256"
    ckn: "847ebcfb9ba54723beded2d736fed7c326847619e72439096f9e95c41414d3a2"
    cak: "4dfb9a53e89b1a93f6a650b3b55b5838"
    interfaces:
      - name: "et-0/0/1.1"
      - name: "et-0/0/1.2"
      - name: "et-0/0/1.3"
      - name: "et-0/0/1.4"
      - name: "et-0/0/1.5"
      - name: "et-0/0/1.6"
      - name: "et-0/0/1.7"
      - name: "et-0/0/1.8"
      - name: "et-0/0/1.9"
      - name: "et-0/0/1.10"
      - name: "et-0/0/1.11"
      - name: "et-0/0/1.12"
      - name: "et-0/0/1.13"
      - name: "et-0/0/1.14"
      - name: "et-0/0/1.15"
      - name: "et-0/0/1.16"
      - name: "et-0/0/1.17"
      - name: "et-0/0/1.18"
      - name: "et-0/0/1.19"
      - name: "et-0/0/1.20"
      - name: "et-0/0/1.21"
      - name: "et-0/0/1.22"
      - name: "et-0/0/1.23"
      - name: "et-0/0/1.24"
      - name: "et-0/0/1.25"
      - name: "et-0/0/1.26"
      - name: "et-0/0/1.27"
      - name: "et-0/0/1.28"
      - name: "et-0/0/1.29"
      - name: "et-0/0/1.30"
      - name: "et-0/0/1.31"
      - name: "et-0/0/1.32"
